steps:
- name: 'gcr.io/cloud-builders/gcloud'
  args:
  - functions
  - deploy
  - calcAngle
  - '--source=https://github.com/JafarShaik6/clocks'
  - '--runtime'
  - python37
  - '--trigger-http'
  - '--allow-unauthenticated'
